CREATE DATABASE ITSkillsDB
GO

USE ITSkillsDB
GO

CREATE TABLE Professions
(Id INT PRIMARY KEY IDENTITY,
Profession NVARCHAR(50) NOT NULL)
GO

CREATE TABLE Employees
(Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Patronymic NVARCHAR(50),
DateOfBirth Date NOT NULL,
ProfessionID INT NOT NULL,
FOREIGN KEY (ProfessionID) REFERENCES Professions (Id) ON DELETE CASCADE)
GO

CREATE TABLE Skills
(Id INT PRIMARY KEY IDENTITY,
Skill NVARCHAR(50) NOT NULL,
ProfessionID INT NOT NULL,
FOREIGN KEY (ProfessionID) REFERENCES Professions (ID) ON DELETE CASCADE)
GO

CREATE TABLE EmployeesSkills
(EmployeeID INT NOT NULL,
SkillID INT NOT NULL,
FOREIGN KEY (EmployeeID) REFERENCES Employees (ID) ON DELETE CASCADE,
CONSTRAINT PK_EmployeeSkills PRIMARY KEY (EmployeeID, SkillID))
GO